// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp65VqfK3ZUAEhtXYziI2HqkCpWf1mkZY',
    appId: '1:56696967029:android:e351e0908946098fa34d3c',
    messagingSenderId: '56696967029',
    projectId: 'to-do-list-70b9c',
    storageBucket: 'to-do-list-70b9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6vWqRRYkImxr_4SDSy_iXsuroDi_YrLc',
    appId: '1:56696967029:ios:46d6d147090c898fa34d3c',
    messagingSenderId: '56696967029',
    projectId: 'to-do-list-70b9c',
    storageBucket: 'to-do-list-70b9c.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWTD7jrsRD4oPQRiSvehqCjdjEi7e8qyc',
    appId: '1:56696967029:web:9850ce24fedce337a34d3c',
    messagingSenderId: '56696967029',
    projectId: 'to-do-list-70b9c',
    authDomain: 'to-do-list-70b9c.firebaseapp.com',
    storageBucket: 'to-do-list-70b9c.appspot.com',
    measurementId: 'G-RVG4CBLFRF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6vWqRRYkImxr_4SDSy_iXsuroDi_YrLc',
    appId: '1:56696967029:ios:46d6d147090c898fa34d3c',
    messagingSenderId: '56696967029',
    projectId: 'to-do-list-70b9c',
    storageBucket: 'to-do-list-70b9c.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWTD7jrsRD4oPQRiSvehqCjdjEi7e8qyc',
    appId: '1:56696967029:web:6d0142a7502ee608a34d3c',
    messagingSenderId: '56696967029',
    projectId: 'to-do-list-70b9c',
    authDomain: 'to-do-list-70b9c.firebaseapp.com',
    storageBucket: 'to-do-list-70b9c.appspot.com',
    measurementId: 'G-J2P3JF6Y9D',
  );

}